# scripts/generate_schema_docs.py
from pathlib import Path
import duckdb

PROCESSED = Path("data/processed")
README = Path("README.md")
START, END = "<!-- BEGIN DATA SCHEMA -->", "<!-- END DATA SCHEMA -->"
con = duckdb.connect()

def table_md(path: Path) -> str:
    src = f"{path}/**/*.parquet" if path.is_dir() else str(path)
    n = con.execute(f"SELECT count(*) FROM '{src}'").fetchone()[0]
    summ = con.execute(f"SUMMARIZE SELECT * FROM '{src}'").df()
    head = (f"### `{path.name}` ({n:,} rows)\n\n"
            "| Column | Type | Null % | Approx. unique |\n|---|---|---|---|")
    rows = [f"| `{r.column_name}` | {r.column_type} | {r.null_percentage} | {r.approx_unique:,} |"
            for r in summ.itertuples()]
    return head + "\n" + "\n".join(rows) + "\n"

paths = sorted([*PROCESSED.glob("*.parquet"), *[d for d in PROCESSED.iterdir() if d.is_dir()]])
section = (f"{START}\n\n## Data schema\n\n"
          "_Auto-generated by `scripts/generate_schema_docs.py`. Do not edit by hand._\n\n"
          + "\n".join(table_md(p) for p in paths) + f"\n{END}")

text = README.read_text()
text = text[:text.index(START)] + section + text[text.index(END) + len(END):]
README.write_text(text)
print("README data schema updated")